In [ ]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [ ]:
from google_play_scraper import reviews, Sort
import pandas as pd


def crawl_reviews(app_id, app_name, total=10000):

    BATCH = 200
    all_reviews = []
    token = None

    while len(all_reviews) < total:

        result, token = reviews(
            app_id,
            lang="vi",
            country="vn",
            sort=Sort.NEWEST,
            count=BATCH,
            continuation_token=token
        )

        if not result:
            break

        all_reviews.extend(result)

        print(f"{app_name}: {len(all_reviews)} dòng")

    all_reviews = all_reviews[:total]

    data = []

    for r in all_reviews:
        data.append({
            "review_id": r["reviewId"],
            "app": app_name,
            "user": r["userName"],
            "rating": r["score"],
            "comment": r["content"].lower(),   # chuyển về lowercase
            "date": r["at"]
        })

    df = pd.DataFrame(data)

    filename = f"{app_name.lower()}_10000.csv"
    df.to_csv(filename, index=False, encoding="utf-8-sig")

    print("Xong:", filename, "| Tổng:", len(df))

    return df


# ===== CHẠY APP =====
crawl_reviews("com.duolingo", "Duolingo")

Duolingo: 200 dòng
Duolingo: 400 dòng
Duolingo: 600 dòng
Duolingo: 800 dòng
Duolingo: 1000 dòng
Duolingo: 1200 dòng
Duolingo: 1400 dòng
Duolingo: 1600 dòng
Duolingo: 1800 dòng
Duolingo: 2000 dòng
Duolingo: 2200 dòng
Duolingo: 2400 dòng
Duolingo: 2600 dòng
Duolingo: 2800 dòng
Duolingo: 3000 dòng
Duolingo: 3200 dòng
Duolingo: 3400 dòng
Duolingo: 3600 dòng
Duolingo: 3800 dòng
Duolingo: 4000 dòng
Duolingo: 4200 dòng
Duolingo: 4400 dòng
Duolingo: 4600 dòng
Duolingo: 4800 dòng
Duolingo: 5000 dòng
Duolingo: 5200 dòng
Duolingo: 5400 dòng
Duolingo: 5600 dòng
Duolingo: 5800 dòng
Duolingo: 6000 dòng
Duolingo: 6200 dòng
Duolingo: 6400 dòng
Duolingo: 6600 dòng
Duolingo: 6800 dòng
Duolingo: 7000 dòng
Duolingo: 7200 dòng
Duolingo: 7400 dòng
Duolingo: 7600 dòng
Duolingo: 7800 dòng
Duolingo: 8000 dòng
Duolingo: 8200 dòng
Duolingo: 8400 dòng
Duolingo: 8600 dòng
Duolingo: 8800 dòng
Duolingo: 9000 dòng
Duolingo: 9200 dòng
Duolingo: 9400 dòng
Duolingo: 9600 dòng
Duolingo: 9800 dòng
Duolingo: 10000 dòng
Xong: duolingo_10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,68cbbe64-5665-4760-868f-5ac221d454f5,Duolingo,Van Phu,4,ok học vui dễ thuộc từ,2026-03-18 05:30:50
1,1d6b7252-70de-4cf4-873a-7c2b11f014e8,Duolingo,Thị An Trần,1,"bị mất x3 ko biết lí do , app lỗi",2026-03-18 05:27:55
2,58a67308-6326-4e3c-8ae6-94d6cc41fdc2,Duolingo,Thanh Nga Trần Thị,5,great,2026-03-18 05:24:06
3,2b802d7d-68ba-410c-89fe-28e419812dc1,Duolingo,YTB Xem,5,hay,2026-03-18 05:22:29
4,4a2215a3-a11a-4f21-ac47-b0d3e250594b,Duolingo,Quỳnh Thu,5,iu em,2026-03-18 05:19:18
...,...,...,...,...,...,...
9995,a8fb1b7a-d050-4bc6-8d79-7b259ec8cfe9,Duolingo,MUI CHAI DANG,5,tuyệt vời 👍,2026-01-10 04:38:25
9996,93666ac7-fc0c-4c29-bf1d-d65c67d9cf83,Duolingo,Phan Thanh hiệp Phan,5,rất hay nên học,2026-01-10 04:35:44
9997,57029127-25cf-40fa-b16d-993b8d950cc9,Duolingo,Trang Phan,4,"cũng được những bài khá ít ,",2026-01-10 04:34:16
9998,ca794048-2657-49fa-ba4c-a3ef24c05b69,Duolingo,Thái Phạm Nam,5,rất thích,2026-01-10 04:29:50
9999,26b28b8b-8790-4020-821c-9a3d333b197e,Duolingo,Phương Trần,5,học đc cả toán cờ vua và âm nhạc và còn học đc...,2026-01-10 04:29:31

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("us.nobarriers.elsa", "ELSA")

ELSA: 200 dòng
ELSA: 400 dòng
ELSA: 600 dòng
ELSA: 800 dòng
ELSA: 1000 dòng
ELSA: 1200 dòng
ELSA: 1400 dòng
ELSA: 1600 dòng
ELSA: 1800 dòng
ELSA: 2000 dòng
ELSA: 2200 dòng
ELSA: 2400 dòng
ELSA: 2600 dòng
ELSA: 2800 dòng
ELSA: 3000 dòng
ELSA: 3200 dòng
ELSA: 3400 dòng
ELSA: 3600 dòng
ELSA: 3800 dòng
ELSA: 4000 dòng
ELSA: 4200 dòng
ELSA: 4400 dòng
ELSA: 4600 dòng
ELSA: 4800 dòng
ELSA: 5000 dòng
ELSA: 5200 dòng
ELSA: 5400 dòng
ELSA: 5600 dòng
ELSA: 5800 dòng
ELSA: 6000 dòng
ELSA: 6200 dòng
ELSA: 6400 dòng
ELSA: 6600 dòng
ELSA: 6800 dòng
ELSA: 7000 dòng
ELSA: 7200 dòng
ELSA: 7400 dòng
ELSA: 7600 dòng
ELSA: 7800 dòng
ELSA: 8000 dòng
ELSA: 8200 dòng
ELSA: 8400 dòng
ELSA: 8600 dòng
ELSA: 8800 dòng
ELSA: 9000 dòng
ELSA: 9200 dòng
ELSA: 9400 dòng
ELSA: 9600 dòng
ELSA: 9800 dòng
ELSA: 10000 dòng
Xong: elsa_10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,143a848d-4cc6-4b03-aaae-1989d168cd49,ELSA,Tien Le,4,good app!,2026-03-17 22:44:57
1,ffdd3a7e-6945-4330-8fd8-535b0a09bbdc,ELSA,Kim xuyến Nguyễn,2,mới học có một bài mà hết lượt học phải chờ 24...,2026-03-17 05:40:25
2,62c452b5-4e53-41d4-b7d3-86e476a666af,ELSA,Thùy Nguyễn,1,viết bản mới này bỏ đi tính năng dịch rồi à. t...,2026-03-14 04:02:16
3,74373647-19f4-4958-8426-d83295389888,ELSA,Bay Duy,5,ứng dụng này rất tuyệt vời,2026-03-13 14:15:37
4,be7434d7-44af-4e10-bc8e-4ac7fbc8c189,ELSA,Gin Phan,1,cập nhật mới khó hiểu và khó sử dụng hơn xưa. ...,2026-03-13 13:22:50
...,...,...,...,...,...,...
9995,08056001-4650-48ec-bd8e-b7b8dddc3416,ELSA,Nguyen Hop,5,rat tuyen,2020-10-13 13:53:36
9996,9dc2e536-6c7c-4b73-b0fe-8fa64936d43c,ELSA,Như Nguyệt,5,ứng dụng này khá tốt,2020-10-13 13:40:57
9997,7faf264a-97fc-4afe-91be-b2dafc4689a0,ELSA,Tường Vy,5,giúp tui học dễ hơn nhiều so với cá,2020-10-13 13:34:31
9998,fa0f5e2a-911f-45fe-8a30-893f5d0482a4,ELSA,Đặng Bông Chip,4,rất tốt,2020-10-13 13:32:34
9999,072e6290-28bd-4b97-8a39-a1ebd7a7e1eb,ELSA,Thị Ngọc Giàu Trần,5,ứng dụng này thật sự rất tuyệt!nó giúp mình cả...,2020-10-13 13:12:28

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.memrise.android.memrisecompanion", "Memrise")

Memrise: 200 dòng
Memrise: 400 dòng
Memrise: 600 dòng
Memrise: 800 dòng
Memrise: 1000 dòng
Memrise: 1200 dòng
Memrise: 1400 dòng
Memrise: 1600 dòng
Memrise: 1800 dòng
Memrise: 2000 dòng
Memrise: 2200 dòng
Memrise: 2400 dòng
Memrise: 2600 dòng
Memrise: 2800 dòng
Memrise: 3000 dòng
Memrise: 3200 dòng
Memrise: 3400 dòng
Memrise: 3600 dòng
Memrise: 3800 dòng
Memrise: 4000 dòng
Memrise: 4200 dòng
Memrise: 4400 dòng
Memrise: 4600 dòng
Memrise: 4800 dòng
Memrise: 5000 dòng
Memrise: 5200 dòng
Memrise: 5400 dòng
Memrise: 5600 dòng
Memrise: 5800 dòng
Memrise: 6000 dòng
Memrise: 6200 dòng
Memrise: 6400 dòng
Memrise: 6600 dòng
Memrise: 6800 dòng
Memrise: 7000 dòng
Memrise: 7200 dòng
Memrise: 7400 dòng
Memrise: 7600 dòng
Memrise: 7800 dòng
Memrise: 8000 dòng
Memrise: 8200 dòng
Memrise: 8400 dòng
Memrise: 8600 dòng
Memrise: 8800 dòng
Memrise: 9000 dòng
Memrise: 9200 dòng
Memrise: 9400 dòng
Memrise: 9600 dòng
Memrise: 9800 dòng
Memrise: 10000 dòng
Xong: memrise_10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,4834bbeb-7748-454e-8d63-0c3f71d455d2,Memrise,Tuấn Lã Anh,1,"app rác, chả có gì để học",2026-03-14 17:34:01
1,6136eae2-fc29-49ad-b546-7c51acdae829,Memrise,Tân Nguyễn Văn,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48
2,5b13b146-12e5-42f8-a23d-4886c40bcb2b,Memrise,ly phương,5,"app này có video thực tế , người bản sứ nói mk...",2026-03-10 18:26:55
3,7d0a5670-1251-4ff2-a464-a164b9bb208f,Memrise,Sơn Nguyễn Văn,5,tốt lắm nha😍,2026-03-06 08:21:25
4,660822fb-a767-448d-beaa-0c809461a0fc,Memrise,зт Д,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32
...,...,...,...,...,...,...
9995,71c7a5e5-8fe0-4041-a730-b59b3d49d4e7,Memrise,Người dùng Google,5,hay,2018-05-28 10:15:47
9996,cbeb84ba-3deb-40b4-bb81-c42d47bebedf,Memrise,Người dùng Google,5,rất tốt!! dễ nhớ từ!!,2018-05-28 04:43:17
9997,de9a4979-f634-41c0-833a-907b74cd3635,Memrise,Người dùng Google,5,hay,2018-05-28 04:30:13
9998,ca98b324-95d5-44d5-8e89-6561dc9d2f0f,Memrise,Người dùng Google,4,tôi mong muốn có cả tiếng pháp. cảm ơn.,2018-05-28 03:06:14
9999,f3d7b3b3-0f1b-4497-9b31-6d34e450648a,Memrise,Người dùng Google,5,app rất hữu ích.,2018-05-28 01:41:51

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("me.mycake", "Cake ")

Cake : 200 dòng
Cake : 400 dòng
Cake : 600 dòng
Cake : 800 dòng
Cake : 1000 dòng
Cake : 1200 dòng
Cake : 1400 dòng
Cake : 1600 dòng
Cake : 1800 dòng
Cake : 2000 dòng
Cake : 2200 dòng
Cake : 2400 dòng
Cake : 2600 dòng
Cake : 2800 dòng
Cake : 3000 dòng
Cake : 3200 dòng
Cake : 3400 dòng
Cake : 3600 dòng
Cake : 3800 dòng
Cake : 4000 dòng
Cake : 4200 dòng
Cake : 4400 dòng
Cake : 4600 dòng
Cake : 4800 dòng
Cake : 5000 dòng
Cake : 5200 dòng
Cake : 5400 dòng
Cake : 5600 dòng
Cake : 5800 dòng
Cake : 6000 dòng
Cake : 6200 dòng
Cake : 6400 dòng
Cake : 6600 dòng
Cake : 6800 dòng
Cake : 7000 dòng
Cake : 7200 dòng
Cake : 7400 dòng
Cake : 7600 dòng
Cake : 7800 dòng
Cake : 8000 dòng
Cake : 8200 dòng
Cake : 8400 dòng
Cake : 8600 dòng
Cake : 8800 dòng
Cake : 9000 dòng
Cake : 9200 dòng
Cake : 9400 dòng
Cake : 9600 dòng
Cake : 9800 dòng
Cake : 10000 dòng
Xong: cake _10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,edf62993-3823-4914-8532-867190551265,Cake,Kiên kun official,5,ok,2026-03-17 06:07:59
1,9441a44a-cba1-4e40-882c-1c981627913a,Cake,Ngọc Berlin Máy Nhôm,5,tốt,2026-03-16 13:40:27
2,9dd5eb30-60e1-4f68-ac53-5297c2d34754,Cake,Thủy Nguyễn thị,5,nó rất thú vị. lag thế,2026-03-16 01:24:16
3,809ae996-9b08-4664-803d-c642ef9518dc,Cake,Ny na,5,dễ thương vậy mă 😍,2026-03-15 10:57:31
4,6f4ad2e2-b234-4fae-b24d-53121ce0e695,Cake,Anh Dương,5,học rất ok nhưng mà pk dùng gói ko đc dùng mp,2026-03-14 14:11:06
...,...,...,...,...,...,...
9995,a4c09a00-ad3a-4f18-94b5-6ad5078914c9,Cake,Hoang Hai Dang,5,good,2022-03-17 12:28:04
9996,c53cd380-2c16-4344-ac6c-6c4058be3c41,Cake,Anh Kim,5,app này khá có ích:),2022-03-17 12:22:37
9997,a1165c57-50c4-4e50-8b6e-f56004b36491,Cake,Phan Loi,5,tôi đã tải về và nó rất thú vị và gây hấp dẫn ...,2022-03-17 11:18:28
9998,362ea624-3982-4d10-8226-2d70a398e1fc,Cake,Nguyện Hồ,5,rất hữu ích hi vọng tiếng anh mình đc cải thiện,2022-03-17 11:05:28
9999,4c99e252-d4aa-490f-a769-ac6b14e6ade8,Cake,tua quoc,5,thích,2022-03-17 11:04:41

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.vn.dic.e.v.ui", "TFlat ")

TFlat : 200 dòng
TFlat : 400 dòng
TFlat : 600 dòng
TFlat : 800 dòng
TFlat : 1000 dòng
TFlat : 1200 dòng
TFlat : 1400 dòng
TFlat : 1600 dòng
TFlat : 1800 dòng
TFlat : 2000 dòng
TFlat : 2200 dòng
TFlat : 2400 dòng
TFlat : 2600 dòng
TFlat : 2800 dòng
TFlat : 3000 dòng
TFlat : 3200 dòng
TFlat : 3400 dòng
TFlat : 3600 dòng
TFlat : 3800 dòng
TFlat : 4000 dòng
TFlat : 4200 dòng
TFlat : 4400 dòng
TFlat : 4600 dòng
TFlat : 4800 dòng
TFlat : 5000 dòng
TFlat : 5200 dòng
TFlat : 5400 dòng
TFlat : 5600 dòng
TFlat : 5800 dòng
TFlat : 6000 dòng
TFlat : 6200 dòng
TFlat : 6400 dòng
TFlat : 6600 dòng
TFlat : 6800 dòng
TFlat : 7000 dòng
TFlat : 7200 dòng
TFlat : 7400 dòng
TFlat : 7600 dòng
TFlat : 7800 dòng
TFlat : 8000 dòng
TFlat : 8200 dòng
TFlat : 8400 dòng
TFlat : 8600 dòng
TFlat : 8800 dòng
TFlat : 9000 dòng
TFlat : 9200 dòng
TFlat : 9400 dòng
TFlat : 9600 dòng
TFlat : 9800 dòng
TFlat : 10000 dòng
Xong: tflat _10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,bc0e43a5-338a-44e8-9987-e01c1f6829ff,TFlat,Nhi Bảo,4,cũng ổn,2026-03-15 06:32:00
1,24f30716-670b-4096-97be-916ba83c6509,TFlat,khoa Nguyễn,5,good,2026-03-14 04:50:23
2,39debc0d-b613-4866-99a3-3defccdaf801,TFlat,duong van tu duong,5,cx ok,2026-03-14 03:34:56
3,f5bb2687-fb15-4dfa-8b1e-1e52ce22892e,TFlat,Thủy Trần,5,tốt vcl,2026-03-14 00:46:34
4,8a42b778-d4e5-4a10-adc0-5fc95c5724ff,TFlat,Nguyễn Công,5,good,2026-03-13 14:04:12
...,...,...,...,...,...,...
9995,a33f46c0-07c5-4205-a615-cb4b0daf7e86,TFlat,Huy Ha,4,chưa đc hiệu quả,2020-08-03 08:35:54
9996,15a1f229-b257-4e5d-9393-6dcc42752c89,TFlat,Trinh Đinh,5,rất ok. đã xài mấy năm nay,2020-08-03 08:29:41
9997,5a5df432-c86d-4e2b-9683-e6170c6b0bdb,TFlat,Hong Tran,5,ok,2020-08-03 08:13:49
9998,a681a0bb-1faa-4b95-881f-6bd89479a740,TFlat,Nhị Võ,5,rất hữu ích,2020-08-03 00:25:55
9999,08507877-6ae5-41de-b340-b176ebc38b50,TFlat,Phạm Đình Nghĩa,5,good,2020-08-02 23:13:38

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.hellotalk", "HelloTalk ")

HelloTalk : 200 dòng
HelloTalk : 400 dòng
HelloTalk : 600 dòng
HelloTalk : 800 dòng
HelloTalk : 1000 dòng
HelloTalk : 1200 dòng
HelloTalk : 1400 dòng
HelloTalk : 1600 dòng
HelloTalk : 1800 dòng
HelloTalk : 1842 dòng
Xong: hellotalk _10000.csv | Tổng: 1842

,review_id,app,user,rating,comment,date
0,5c27fb11-2d7a-4649-bbe4-ba2343b67b29,HelloTalk,Hằng Phạm,1,có sticker happy chinese new year nha mn app q...,2026-03-14 03:38:43
1,67fca727-f835-4659-8be2-88608827cc91,HelloTalk,Ngọc Luu,1,sao lại happy chinese new year,2026-03-14 03:33:44
2,1433fdbb-ec4b-4004-bee0-cab78238dc62,HelloTalk,Hân Lê,5,tôi kiếm dc nhiều bạn mới,2026-03-10 14:18:45
3,62d23a31-a9a1-4f83-8bfc-aa8fb95d82f0,HelloTalk,Dạu Ngô,1,không có trải nghiệm tốt cả .. rất tệ,2026-03-10 12:49:33
4,552a4046-5c18-4356-9481-704c0bacce9a,HelloTalk,An Triệu,5,đa số là người trung🇨🇳🇨🇳,2026-03-09 22:26:54
...,...,...,...,...,...,...
1837,944e29e6-5145-44da-8c9c-8a36a16278d7,HelloTalk,Người dùng Google,3,tuyet,2015-04-20 12:18:22
1838,be774359-5535-4c12-ac66-006c1ff22798,HelloTalk,Người dùng Google,5,hay,2015-04-19 05:11:21
1839,611c2298-01f6-4b8e-bba3-5783b0572cf6,HelloTalk,Người dùng Google,1,lừa đảo,2015-04-12 14:55:44
1840,50ff8565-af75-4612-a903-29d11c928eb8,HelloTalk,Người dùng Google,4,can't download. can you fix it???,2015-01-03 16:55:23
1841,4ec67044-950a-4bb3-8d5e-708ce9261283,HelloTalk,Người dùng Google,5,hay,2014-09-22 16:40:47

In [ ]:
from google_play_scraper import reviews, Sort
import pandas as pd

def crawl_reviews(app_id, app_name, total=10000):

    BATCH = 200
    all_reviews = []
    token = None

    while len(all_reviews) < total:

        result, token = reviews(
            app_id,
            lang="vi",
            country="vn",
            sort=Sort.NEWEST,
            count=BATCH,
            continuation_token=token
        )

        if not result:
            break

        all_reviews.extend(result)

        print(f"{app_name}: {len(all_reviews)} dòng")

    all_reviews = all_reviews[:total]

    data = []

    for r in all_reviews:
        data.append({
            "review_id": r["reviewId"],
            "app": app_name,
            "user": r["userName"],
            "rating": r["score"],
            "comment": (r["content"] or "").lower(),   # Handle None content and convert to lowercase
            "date": r["at"]
        })

    df = pd.DataFrame(data)

    filename = f"{app_name.lower()}_10000.csv"
    df.to_csv(filename, index=False, encoding="utf-8-sig")

    print("Xong:", filename, "| Tổng:", len(df))

    return df


# ===== CHẠY APP =====
crawl_reviews("com.busuu.android.enc", "Busuu")

Busuu: 200 dòng
Busuu: 400 dòng
Busuu: 600 dòng
Busuu: 800 dòng
Busuu: 1000 dòng
Busuu: 1200 dòng
Busuu: 1400 dòng
Busuu: 1600 dòng
Busuu: 1800 dòng
Busuu: 1952 dòng
Xong: busuu_10000.csv | Tổng: 1952

,review_id,app,user,rating,comment,date
0,9e955bf2-2873-4c14-8bb5-fb578934c078,Busuu,Ba Truong,5,hay vi ci eo. ilovebusuu,2026-03-07 12:35:41
1,47dad7a2-994c-4ada-a718-967cc003fa1d,Busuu,Giang Quỳnh,2,i can't access the application.,2026-03-03 12:09:03
2,65f25133-3121-4186-ba92-0cc1ad4540fa,Busuu,Diêu my Drong,5,oki lém,2026-03-02 10:01:08
3,90cad131-61db-45af-8963-6da61a50c271,Busuu,Nhiên An,5,ok á,2026-02-27 09:29:47
4,d36e0ba3-01a8-43f9-a799-792cccdc4624,Busuu,Đạt Phạm,1,trò truyện với ai không dùng được,2026-02-24 12:00:54
...,...,...,...,...,...,...
1947,e41ca976-1109-46f5-84f1-6a99cd0fad81,Busuu,Người dùng Google,5,"tot wa,minh dag can nhug phan mem nhu the nay,...",2012-06-15 02:49:43
1948,718195c6-5b01-4eba-88dc-9b9dd203a381,Busuu,Người dùng Google,5,very good,2012-06-12 01:04:39
1949,80592855-8cb1-403e-b7aa-91db833116f8,Busuu,Người dùng Google,4,good,2012-04-07 14:12:16
1950,259b489e-6f02-48a6-9b9f-67f934c8cf96,Busuu,Người dùng Google,4,great!,2012-03-17 11:45:59
1951,dcefb8d7-d8b7-42a5-beae-af34953d274f,Busuu,Người dùng Google,5,i like it very much bit i need more,2011-10-23 10:30:51

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.lingodeer", "LingoDeer")

LingoDeer: 200 dòng
LingoDeer: 400 dòng
LingoDeer: 600 dòng
LingoDeer: 800 dòng
LingoDeer: 1000 dòng
LingoDeer: 1200 dòng
LingoDeer: 1400 dòng
LingoDeer: 1600 dòng
LingoDeer: 1800 dòng
LingoDeer: 2000 dòng
LingoDeer: 2200 dòng
LingoDeer: 2400 dòng
LingoDeer: 2600 dòng
LingoDeer: 2800 dòng
LingoDeer: 3000 dòng
LingoDeer: 3200 dòng
LingoDeer: 3400 dòng
LingoDeer: 3600 dòng
LingoDeer: 3800 dòng
LingoDeer: 4000 dòng
LingoDeer: 4200 dòng
LingoDeer: 4400 dòng
LingoDeer: 4600 dòng
LingoDeer: 4800 dòng
LingoDeer: 5000 dòng
LingoDeer: 5200 dòng
LingoDeer: 5400 dòng
LingoDeer: 5600 dòng
LingoDeer: 5800 dòng
LingoDeer: 6000 dòng
LingoDeer: 6200 dòng
LingoDeer: 6400 dòng
LingoDeer: 6600 dòng
LingoDeer: 6800 dòng
LingoDeer: 7000 dòng
LingoDeer: 7200 dòng
LingoDeer: 7400 dòng
LingoDeer: 7600 dòng
LingoDeer: 7800 dòng
LingoDeer: 8000 dòng
LingoDeer: 8200 dòng
LingoDeer: 8400 dòng
LingoDeer: 8600 dòng
LingoDeer: 8800 dòng
LingoDeer: 9000 dòng
LingoDeer: 9200 dòng
LingoDeer: 9400 dòng
LingoDeer: 9600 dòng
LingoDeer: 9800 dòng
LingoDeer: 10000 dòng
Xong: lingodeer_10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,bede992a-70e2-4fd1-8147-f9a39d4547bb,LingoDeer,Noy Noii,3,i like this app because i looking app study ne...,2026-03-12 16:44:15
1,af0e962d-c391-48b7-a851-4525823d02ea,LingoDeer,Hạnh Nguyen,4,tốt,2026-03-12 06:49:13
2,13515a61-6885-42a8-897f-f71d902d5ba4,LingoDeer,Truc Thanh,5,"ok nè có đọc, nghe , nói ,... luyện tập nữa 🥰",2026-03-11 17:12:22
3,6fa36d55-25ce-4a98-a4cf-789b4b9e1927,LingoDeer,Hoang Thi Trang,5,"học rất ok, good good",2026-03-11 12:58:04
4,e5c82fc5-1362-4144-b503-03cd93834039,LingoDeer,Khánh duy Nguyễn,3,tôi đã đăng ký và đã hiện gói và trừ tiền nhưn...,2026-03-11 02:48:08
...,...,...,...,...,...,...
9995,82e7c882-fb67-4d4a-9634-faf1ecc36315,LingoDeer,Người dùng Google,5,rat hay,2019-06-16 01:52:41
9996,09ac8878-bdf4-4e65-b5f2-1c671efb1be9,LingoDeer,Người dùng Google,5,tuyệt vời,2019-06-16 01:36:47
9997,9b950879-685e-4611-9d81-035a1a882952,LingoDeer,Người dùng Google,4,thích,2019-06-16 00:38:38
9998,a460bfe0-3cd4-4124-b64e-f2eae050898d,LingoDeer,Người dùng Google,4,tốt,2019-06-16 00:12:08
9999,b4735e60-4f99-49c9-8f6d-ebc706da3c51,LingoDeer,Người dùng Google,5,rất hay,2019-06-15 23:16:24

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.quizlet.quizletandroid", "Quizlet")

Quizlet: 200 dòng
Quizlet: 400 dòng
Quizlet: 600 dòng
Quizlet: 800 dòng
Quizlet: 1000 dòng
Quizlet: 1200 dòng
Quizlet: 1400 dòng
Quizlet: 1600 dòng
Quizlet: 1800 dòng
Quizlet: 2000 dòng
Quizlet: 2200 dòng
Quizlet: 2400 dòng
Quizlet: 2600 dòng
Quizlet: 2800 dòng
Quizlet: 3000 dòng
Quizlet: 3200 dòng
Quizlet: 3400 dòng
Quizlet: 3600 dòng
Quizlet: 3800 dòng
Quizlet: 4000 dòng
Quizlet: 4200 dòng
Quizlet: 4400 dòng
Quizlet: 4600 dòng
Quizlet: 4800 dòng
Quizlet: 5000 dòng
Quizlet: 5200 dòng
Quizlet: 5400 dòng
Quizlet: 5600 dòng
Quizlet: 5800 dòng
Quizlet: 6000 dòng
Quizlet: 6200 dòng
Quizlet: 6400 dòng
Quizlet: 6600 dòng
Quizlet: 6800 dòng
Quizlet: 7000 dòng
Quizlet: 7200 dòng
Quizlet: 7400 dòng
Quizlet: 7600 dòng
Quizlet: 7800 dòng
Quizlet: 8000 dòng
Quizlet: 8200 dòng
Quizlet: 8400 dòng
Quizlet: 8600 dòng
Quizlet: 8800 dòng
Quizlet: 9000 dòng
Quizlet: 9200 dòng
Quizlet: 9400 dòng
Quizlet: 9600 dòng
Quizlet: 9800 dòng
Quizlet: 10000 dòng
Xong: quizlet_10000.csv | Tổng: 10000

,review_id,app,user,rating,comment,date
0,f0e5dda4-d401-40f4-83a7-90b59b510f8a,Quizlet,Việt Hoàng,1,cái đếch gì cũng học đc tý xog đòi mua premium...,2026-03-17 22:37:58
1,f4d33374-a4b1-43d6-96cb-0c1855de83f9,Quizlet,Trinh Thanh Huyen,4,k free,2026-03-17 15:48:33
2,0482e62a-8c91-4d6a-ac07-4302002f0914,Quizlet,Celina,3,chi phí đắt,2026-03-17 13:31:55
3,b330bf76-8e89-4de4-8202-d83934fcc268,Quizlet,Nam Dinh,5,hay,2026-03-17 11:52:11
4,785f3d89-307d-411e-8af5-9208b6b27163,Quizlet,Bảo Vũ,2,ngày trước thì học ngon bây giờ đang học dở cá...,2026-03-16 11:29:31
...,...,...,...,...,...,...
9995,f4685dbf-8a53-4432-8c3e-f75082fa35b0,Quizlet,Người dùng Google,5,very good,2019-01-12 09:50:18
9996,0d080ce7-2467-44a2-97a9-48041269d2da,Quizlet,Người dùng Google,5,"rất hữu dụng, học tập rất tốt!",2019-01-10 09:44:06
9997,94450b23-e16e-4fab-93ec-c975c4a0c727,Quizlet,Người dùng Google,5,it's really helpful,2019-01-10 05:48:01
9998,2af439e3-9f76-48bd-b58a-8cc4c8aea97c,Quizlet,Người dùng Google,4,"it's good app for learning, but pronouncing no...",2019-01-09 11:56:12
9999,fb72de33-75ec-4e25-a71d-f1eeb8507492,Quizlet,Người dùng Google,5,good,2019-01-09 08:49:15

In [ ]:
# ===== CHẠY APP =====
crawl_reviews("com.ted.android", "TED Talks")

TED Talks: 200 dòng
TED Talks: 400 dòng
TED Talks: 600 dòng
TED Talks: 800 dòng
TED Talks: 834 dòng
Xong: ted talks_10000.csv | Tổng: 834

,review_id,app,user,rating,comment,date
0,9a0d6182-b314-4e3d-9deb-5e888f90e225,TED Talks,Anh Dung,1,thường xuyên không thể phát. quá là tệ hại,2025-12-18 00:11:12
1,7a75e87d-6a38-44a2-a29b-ae57fcaadc7c,TED Talks,Người dùng Google,5,good,2025-12-06 09:29:17
2,93b97ae8-3877-4ed4-8cde-5fcf289cad1f,TED Talks,Văn Hữu Trần,5,great!,2025-10-30 05:24:37
3,3d6fb747-e75b-4a06-9556-7c40a6b68861,TED Talks,Nguyen Nguyen,5,so helpful but too lag,2025-10-21 12:02:48
4,ae8d50fa-ecd7-48dc-8fb7-6f5fc482e922,TED Talks,Tuyên Trịnh,5,what a nice app recommended by chris - ielts a...,2025-08-27 03:05:23
...,...,...,...,...,...,...
829,91934ac2-4d54-4920-854a-d4f6e896ac2b,TED Talks,Người dùng Google,5,:-),2013-02-22 06:15:59
830,e7041525-b9eb-4c64-885c-8740b566574e,TED Talks,Người dùng Google,5,very good. it's necessary for learning english.,2013-01-01 04:49:29
831,b9ab1f1a-4987-42e9-9fa9-d8e6b5297725,TED Talks,Người dùng Google,5,hay!,2012-08-29 14:57:20
832,3f3ec0e7-aa84-4099-9d61-6a867e068cd0,TED Talks,Người dùng Google,5,những bài diễn văn đầy ý nghĩa,2012-08-22 09:47:52
833,825b812a-f7ec-4548-a733-be271be87382,TED Talks,Người dùng Google,3,bài nói chuyện ở ted rất tuyệt chương trình c...,2012-08-03 14:06:42

In [ ]:
import pandas as pd
import glob

# lấy tất cả file csv trong folder
files = glob.glob("*.csv")

# đọc và gộp
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

# kiểm tra số dòng
print("Total rows:", len(df))

# lưu file tổng
df.to_csv("english_learning_apps_reviews.csv", index=False, encoding="utf-8-sig")

print("Đã xuất file: english_learning_apps_reviews.csv")

Total rows: 74628
Đã xuất file: english_learning_apps_reviews.csv

In [ ]:
df.head()

,review_id,app,user,rating,comment,date
0,4834bbeb-7748-454e-8d63-0c3f71d455d2,Memrise,Tuấn Lã Anh,1,"app rác, chả có gì để học",2026-03-14 17:34:01
1,6136eae2-fc29-49ad-b546-7c51acdae829,Memrise,Tân Nguyễn Văn,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48
2,5b13b146-12e5-42f8-a23d-4886c40bcb2b,Memrise,ly phương,5,"app này có video thực tế , người bản sứ nói mk...",2026-03-10 18:26:55
3,7d0a5670-1251-4ff2-a464-a164b9bb208f,Memrise,Sơn Nguyễn Văn,5,tốt lắm nha😍,2026-03-06 08:21:25
4,660822fb-a767-448d-beaa-0c809461a0fc,Memrise,зт Д,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32

In [ ]:
df.info()
# There is null value in 'comment' column
# The data type of 'date' column is not suitable, it should be datetime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74628 entries, 0 to 74627
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review_id  74628 non-null  object
 1   app        74628 non-null  object
 2   user       74628 non-null  object
 3   rating     74628 non-null  int64
 4   comment    74621 non-null  object
 5   date       74628 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.4+ MB

In [ ]:
# Drop rows containing Null value
df.dropna(subset=['comment'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74621 entries, 0 to 74627
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review_id  74621 non-null  object
 1   app        74621 non-null  object
 2   user       74621 non-null  object
 3   rating     74621 non-null  int64
 4   comment    74621 non-null  object
 5   date       74621 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.0+ MB

In [ ]:
# Change data type of 'date' column to datetime
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74621 entries, 0 to 74627
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review_id  74621 non-null  object
 1   app        74621 non-null  object
 2   user       74621 non-null  object
 3   rating     74621 non-null  int64
 4   comment    74621 non-null  object
 5   date       74621 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 4.0+ MB

In [ ]:
num_unique_reviews = df['review_id'].nunique()
total_reviews = len(df)

print(f"Number of unique review_id values: {num_unique_reviews}")
print(f"Total number of reviews: {total_reviews}")

if num_unique_reviews == total_reviews:
    print("All review_id values are distinct.")
else:
    print("There are duplicate review_id values.")

Number of unique review_id values: 74621
Total number of reviews: 74621
All review_id values are distinct.

In [ ]:
df = df.rename(columns={'app': 'app_id'})

app_id_mapping = {
    'Duolingo': 1,
    'ELSA': 2,
    'Memrise': 3,
    'Cake ': 4,
    'TFlat ': 5,
    'HelloTalk ': 6,
    'Busuu': 7,
    'LingoDeer': 8,
    'Quizlet': 9,
    'TED Talks': 10
}

df['app_id'] = df['app_id'].replace(app_id_mapping)

display(df.head())

/tmp/ipykernel_1040/391580718.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['app_id'] = df['app_id'].replace(app_id_mapping)

,review_id,app_id,user,rating,comment,date
0,4834bbeb-7748-454e-8d63-0c3f71d455d2,3,Tuấn Lã Anh,1,"app rác, chả có gì để học",2026-03-14 17:34:01
1,6136eae2-fc29-49ad-b546-7c51acdae829,3,Tân Nguyễn Văn,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48
2,5b13b146-12e5-42f8-a23d-4886c40bcb2b,3,ly phương,5,"app này có video thực tế , người bản sứ nói mk...",2026-03-10 18:26:55
3,7d0a5670-1251-4ff2-a464-a164b9bb208f,3,Sơn Nguyễn Văn,5,tốt lắm nha😍,2026-03-06 08:21:25
4,660822fb-a767-448d-beaa-0c809461a0fc,3,зт Д,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32

In [ ]:
df.drop('user', axis=1, inplace=True)
df.head()

KeyError: "['user'] not found in axis"

In [ ]:
df.head()

,review_id,app_id,rating,comment,date
0,4834bbeb-7748-454e-8d63-0c3f71d455d2,3,1,"app rác, chả có gì để học",2026-03-14 17:34:01
1,6136eae2-fc29-49ad-b546-7c51acdae829,3,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48
2,5b13b146-12e5-42f8-a23d-4886c40bcb2b,3,5,"app này có video thực tế , người bản sứ nói mk...",2026-03-10 18:26:55
3,7d0a5670-1251-4ff2-a464-a164b9bb208f,3,5,tốt lắm nha😍,2026-03-06 08:21:25
4,660822fb-a767-448d-beaa-0c809461a0fc,3,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32

In [ ]:
import re

# chỉ giữ comment có chữ cái, số và khoảng trắng
df_clean = df[df['comment'].str.match(r'^[A-Za-z0-9\s]+$', na=False)]

In [ ]:
import pandas as pd

# Đếm số từ trong mỗi comment
df['word_count'] = df['comment'].str.split().apply(len)

# Giữ lại comment có >= 10 từ
df_filtered = df[df['word_count'] >= 25]

print("Original comments:", len(df))
print("Filtered comments:", len(df_filtered))

Original comments: 74621
Filtered comments: 5037

In [ ]:
df_filtered.head()

,review_id,app_id,rating,comment,date,word_count
1,6136eae2-fc29-49ad-b546-7c51acdae829,3,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48,53
4,660822fb-a767-448d-beaa-0c809461a0fc,3,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32,50
5,23902468-e944-4b1e-8207-561d0897a541,3,5,"ứng dụng tuyệt vời nhất. không phí, không quản...",2026-02-22 03:37:41,41
12,81acb682-129e-4c28-884b-1be89a677642,3,2,fix nhiều lỗi là cho 5 sao nhé ( lỗi 1: ấn vào...,2025-12-12 14:08:24,38
15,9c4fed55-0e7a-465a-b5fd-83cb696de337,3,4,"[!]to enhance the user experience, we propose ...",2025-11-25 07:09:07,56

In [ ]:
len(df_filtered)

5037

In [ ]:
import numpy as np

conditions = [
    (df_filtered['rating'] <= 2),
    (df_filtered['rating'] >= 4),
    (df_filtered['rating'] == 3)
]
choices = ['Negative', 'Positive', 'Neutral']

df_filtered['sentiment'] = np.select(conditions, choices, default='Unknown')

display(df_filtered.head())

/tmp/ipykernel_1040/1358407449.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['sentiment'] = np.select(conditions, choices, default='Unknown')

,review_id,app_id,rating,comment,date,word_count,sentiment
1,6136eae2-fc29-49ad-b546-7c51acdae829,3,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48,53,Neutral
4,660822fb-a767-448d-beaa-0c809461a0fc,3,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32,50,Negative
5,23902468-e944-4b1e-8207-561d0897a541,3,5,"ứng dụng tuyệt vời nhất. không phí, không quản...",2026-02-22 03:37:41,41,Positive
12,81acb682-129e-4c28-884b-1be89a677642,3,2,fix nhiều lỗi là cho 5 sao nhé ( lỗi 1: ấn vào...,2025-12-12 14:08:24,38,Negative
15,9c4fed55-0e7a-465a-b5fd-83cb696de337,3,4,"[!]to enhance the user experience, we propose ...",2025-11-25 07:09:07,56,Positive

In [ ]:
df_positive = df_filtered[df_filtered['sentiment'] == 'Positive']
df_negative = df_filtered[df_filtered['sentiment'] == 'Negative']
df_neutral = df_filtered[df_filtered['sentiment'] == 'Neutral']

print(f"Number of Positive reviews: {len(df_positive)}")
print(f"Number of Negative reviews: {len(df_negative)}")
print(f"Number of Neutral reviews: {len(df_neutral)}")

Number of Positive reviews: 3178
Number of Negative reviews: 1370
Number of Neutral reviews: 489

In [ ]:
num_positive_reviews = len(df_positive)
midpoint = num_positive_reviews // 2

df_positive_1 = df_positive.iloc[:midpoint].copy()
df_positive_2 = df_positive.iloc[midpoint:].copy()

print(f"Number of Positive reviews (Part 1): {len(df_positive_1)}")
print(f"Number of Positive reviews (Part 2): {len(df_positive_2)}")

Number of Positive reviews (Part 1): 1589
Number of Positive reviews (Part 2): 1589

In [ ]:
print(f"\n--- df_positive_1 ({len(df_positive_1)} rows) ---")
display(df_positive_1.head())

print(f"\n--- df_positive_2 ({len(df_positive_2)} rows) ---")
display(df_positive_2.head())

print(f"\n--- df_negative ({len(df_negative)} rows) ---")
display(df_negative.head())

print(f"\n--- df_neutral ({len(df_neutral)} rows) ---")
display(df_neutral.head())

--- df_positive_1 (1589 rows) ---

,review_id,app_id,rating,comment,date,word_count,sentiment
5,23902468-e944-4b1e-8207-561d0897a541,3,5,"ứng dụng tuyệt vời nhất. không phí, không quản...",2026-02-22 03:37:41,41,Positive
15,9c4fed55-0e7a-465a-b5fd-83cb696de337,3,4,"[!]to enhance the user experience, we propose ...",2025-11-25 07:09:07,56,Positive
23,e5c32044-759a-4ffc-8b3c-3e86337b7d93,3,4,why don’t you combine the community courses wi...,2025-09-28 06:54:26,30,Positive
31,79629a96-3b24-4ee1-a9b7-0afd1cb71cb2,3,5,app này vừa học cụm từ vừa học từ lại còn học ...,2025-09-07 11:01:58,49,Positive
42,c6539ada-2329-483d-af9f-54de1c587914,3,4,các bạn không còn tôn trọng khách hàng nữa. cá...,2025-08-14 15:02:54,60,Positive

--- df_positive_2 (1589 rows) ---

,review_id,app_id,rating,comment,date,word_count,sentiment
35546,dfc61d55-da7e-4d99-8e13-c64a8d38a483,1,5,"áp học này rất tốt để rèn luyện lâu ngày, áp n...",2026-02-24 14:40:30,36,Positive
35552,9a5ce408-0672-4e04-95fe-ef9dd373c9ea,1,5,học thấy rất bổ ích.những bài học luôn đem lại...,2026-02-24 13:50:48,45,Positive
35560,16dc8b9e-f78d-4999-9845-3e637330a080,1,4,tôi rất thích doulingo vì nó giúp tôi học mọi ...,2026-02-24 13:03:07,30,Positive
35663,0e5beca8-b89e-4016-8c6c-44f10b4ef1ee,1,5,tui khuyên mấy bạn muốn học ngoại ngữ hiệu quả...,2026-02-23 14:26:09,70,Positive
35672,c56e3f8e-aadd-4f0e-b1a6-2fb4fb8fca56,1,5,tốt nhưng cần bổ sung bài tập kiểu như là bài ...,2026-02-23 13:40:20,25,Positive

--- df_negative (1370 rows) ---

,review_id,app_id,rating,comment,date,word_count,sentiment
4,660822fb-a767-448d-beaa-0c809461a0fc,3,2,sao lúc trước app vẫn dùng bình thường mà bây ...,2026-03-05 16:27:32,50,Negative
12,81acb682-129e-4c28-884b-1be89a677642,3,2,fix nhiều lỗi là cho 5 sao nhé ( lỗi 1: ấn vào...,2025-12-12 14:08:24,38,Negative
55,bba63368-41e7-436f-9d2b-4e48217a43cb,3,1,"nó bị lỗi trời ơi,cái phần nghe cứ hiện lên ""c...",2025-07-21 14:19:00,42,Negative
62,2944bbea-e91f-43f7-875d-0df56cf197c8,3,1,"mình dùng memrise từ 2013, và vì tin tưởng các...",2025-07-02 18:26:26,69,Negative
122,c84e010f-3c64-46a5-a4f1-b1dab9df2167,3,2,thấy đánh giá ok đó nhưng mà. người việt thì k...,2025-02-19 13:12:48,38,Negative

--- df_neutral (489 rows) ---

,review_id,app_id,rating,comment,date,word_count,sentiment
1,6136eae2-fc29-49ad-b546-7c51acdae829,3,3,app tạm ổn học từ vựng thì nên hiển thị thêm p...,2026-03-12 12:55:48,53,Neutral
34,17d76195-1111-49d5-8586-b383bac139ed,3,3,mấy nay nó bị sao á tui vô mà nó bắt chọn ngôn...,2025-09-05 01:37:16,30,Neutral
77,9a82d8cb-95fe-4c67-99c6-51083e870fd3,3,3,ứng dụng khá hay nhưng chi phí mình thấy đắt q...,2025-06-03 18:56:01,43,Neutral
92,de378ff9-814d-44f5-a129-c96ef35d9a0f,3,3,tôi mới vừa phải thôi nhưng chưa vào để xem th...,2025-05-08 04:25:20,27,Neutral
121,4a3317f9-ef99-485f-9452-e96f692c6176,3,3,học tiếng trung: mình đánh giá cao việc ứng dụ...,2025-02-21 03:49:12,108,Neutral

In [ ]:
pip install googletrans==4.0.0-rc1

In [ ]:
from googletrans import Translator
import time

translator = Translator()

def translate_comment(comment):
    try:
        # Add a small delay to avoid hitting rate limits
        time.sleep(0.1) # Wait for 100 milliseconds
        translated = translator.translate(comment, src='vi', dest='en')
        return translated.text
    except Exception as e:
        print(f"Error translating comment: {comment[:50]}... Error: {e}")
        return None

df_positive_1['comment_en'] = df_positive_1['comment'].astype(str).apply(translate_comment)

df_positive_1.head()

In [ ]:
df_positive_2['comment_en'] = df_positive_2['comment'].astype(str).apply(translate_comment)
df_positive_2.head()

In [ ]:
df_negative['comment_en'] = df_negative['comment'].astype(str).apply(translate_comment)
df_negative.head()

In [ ]:
df_neutral['comment_en'] = df_neutral['comment'].astype(str).apply(translate_comment)
df_neutral.head()

In [ ]:
df_positive_1.to_csv("positive_reviews_part1_translated.csv", index=False, encoding="utf-8-sig")
df_positive_2.to_csv("positive_reviews_part2_translated.csv", index=False, encoding="utf-8-sig")
df_negative.to_csv("negative_reviews_translated.csv", index=False, encoding="utf-8-sig")
df_neutral.to_csv("neutral_comments.csv", index=False, encoding="utf-8-sig")